services:
  - type: web
    name: ai-video-clipper
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && pip install --upgrade yt-dlp
    startCommand: gunicorn -w 2 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
